package com.guo.pets.domain;

public class Profile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pets-profile.id
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pets-profile.user_name
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pets-profile.user_password
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pets-profile.sex
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pets-profile.address
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pets-profile.phone
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pets-profile.mail
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    private String mail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pets-profile.id
     *
     * @return the value of pets-profile.id
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pets-profile.id
     *
     * @param id the value for pets-profile.id
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pets-profile.user_name
     *
     * @return the value of pets-profile.user_name
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pets-profile.user_name
     *
     * @param userName the value for pets-profile.user_name
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pets-profile.user_password
     *
     * @return the value of pets-profile.user_password
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pets-profile.user_password
     *
     * @param userPassword the value for pets-profile.user_password
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pets-profile.sex
     *
     * @return the value of pets-profile.sex
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pets-profile.sex
     *
     * @param sex the value for pets-profile.sex
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pets-profile.address
     *
     * @return the value of pets-profile.address
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pets-profile.address
     *
     * @param address the value for pets-profile.address
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pets-profile.phone
     *
     * @return the value of pets-profile.phone
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pets-profile.phone
     *
     * @param phone the value for pets-profile.phone
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pets-profile.mail
     *
     * @return the value of pets-profile.mail
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pets-profile.mail
     *
     * @param mail the value for pets-profile.mail
     *
     * @mbg.generated Wed Mar 14 22:21:41 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail;
    }
}